name: biodiversity lovers
favicon: null
layout_spectrum: 0.08962094830349088
typography_spectrum: 0.51332
title: 'We are biodiversity lovers publishing content we discover in the real live and from the internet '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0d10'
    - '#daffc9'
    - '#f59d85'
    - '#52a62d'
    - '#8f0010'
  brandStrength: 0.16996154142543674
  lightness: 0.24237131769768894
  saturation: 0
  rhythmicContrast: 0.5813278197310865
purpose: []
