name: biodiversity lovers
favicon: null
layout_spectrum: 0.50717
typography_spectrum: 0.75922
title: 'We are biodiversity lovers publishing content we discover in the real live and from the internet '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad5b8'
    - '#506d4e'
    - '#738c65'
    - '#a2a764'
    - '#304828'
  brandStrength: 0.16996154142543674
  lightness: 0.24237131769768894
  saturation: 0
  rhythmicContrast: 0.5813278197310865
purpose: []
